// Auto-generated by fix-prefs.js
// prettier-ignore
// eslint-disable
// @ts-nocheck

declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      engine: string;
      apiMode: string;
      noteNaming: string;
      customNamingTemplate: string;
      autoOCR: boolean;
      concurrency: number;
      endpoints: string;
      advancedFeatures: string;
    };
  }
}
