import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const pkg = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "package.json"), "utf-8"),
);
const prefix = pkg.config.prefsPrefix;

const buildDir = path.join(__dirname, "..", ".scaffold", "build", "addon");
const prefsFile = path.join(buildDir, "prefs.js");

const prefs = [
  { key: "engine", type: "string", value: "PP-OCRv5" },
  { key: "apiMode", type: "string", value: "sync" },
  { key: "noteNaming", type: "string", value: "default" },
  { key: "customNamingTemplate", type: "string", value: "{{ firstCreator suffix=' - ' }}{{ year suffix=' - ' }}OCR Result" },
  { key: "autoOCR", type: "boolean", value: false },
  { key: "concurrency", type: "integer", value: 3 },
  { key: "endpoints", type: "string", value: "{}" },
  { key: "advancedFeatures", type: "string", value: "{}" },
];

let content = "";
for (const pref of prefs) {
  const fullKey = `${prefix}.${pref.key}`;
  if (pref.type === "string") {
    content += `pref("${fullKey}", "${pref.value}");\n`;
  } else if (pref.type === "boolean") {
    content += `pref("${fullKey}", ${pref.value});\n`;
  } else if (pref.type === "integer") {
    content += `pref("${fullKey}", ${pref.value});\n`;
  }
}

fs.writeFileSync(prefsFile, content, "utf-8");
console.log("Fixed prefs.js in build output");

const xhtmlFile = path.join(buildDir, "content", "preferences.xhtml");
if (fs.existsSync(xhtmlFile)) {
  let xhtmlContent = fs.readFileSync(xhtmlFile, "utf-8");
  for (const pref of prefs) {
    const regex = new RegExp(
      `preference="${pref.key}"`,
      "g",
    );
    xhtmlContent = xhtmlContent.replace(
      regex,
      `preference="${prefix}.${pref.key}"`,
    );
  }
  fs.writeFileSync(xhtmlFile, xhtmlContent, "utf-8");
  console.log("Fixed preferences.xhtml preference attributes");
}

const typingsDir = path.join(__dirname, "..", "typings");
const prefsTypesFile = path.join(typingsDir, "prefs.d.ts");

const typeMap = {
  string: "string",
  boolean: "boolean",
  integer: "number",
};

let typeContent = `// Auto-generated by fix-prefs.js\n`;
typeContent += `// prettier-ignore\n`;
typeContent += `// eslint-disable\n`;
typeContent += `// @ts-nocheck\n\n`;
typeContent += `declare namespace _ZoteroTypes {\n`;
typeContent += `  interface Prefs {\n`;
typeContent += `    PluginPrefsMap: {\n`;
for (const pref of prefs) {
  typeContent += `      ${pref.key}: ${typeMap[pref.type]};\n`;
}
typeContent += `    };\n`;
typeContent += `  }\n`;
typeContent += `}\n`;

fs.writeFileSync(prefsTypesFile, typeContent, "utf-8");
console.log("Fixed prefs.d.ts typings");
